language: ruby
rvm:
  - 2.1.5

addons:
  code_climate:
    repo_token:

env:
  global:
    - RUBY_GC_MALLOC_LIMIT=90000000
    - RUBY_GC_HEAP_FREE_SLOTS=200000
    - SECURITY_SECRET_TOKEN=traviscitraviscitraviscitraviscitravisci

services:
  - postgresql
  - redis-server

before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c "CREATE USER listn_api WITH PASSWORD 'listn_api';" -U postgres
  - psql -c "DROP DATABASE IF EXISTS listn_api_test;" -U postgres
  - psql -c "CREATE DATABASE listn_api_test ENCODING 'utf8';" -U postgres
  - bundle exec rake db:migrate test:prepare

script:
  - bundle exec rspec
  - bundle exec cucumber
  - bundle exec rubocop app spec features -R --format simple

notifications:
  email:
    recipients:
      - listn_api-dev@wolox.com.ar

cache:
  bundler: true
